/**
 * RazorTool — Phase 2 Step 2
 *
 * Click on a clip at any frame → split it into two clips at that frame.
 * Shift+click (ctx.modifiers.shift) → split ALL clips at that frame across ALL tracks.
 *
 * CONTRACT:
 *   - No drag, no provisional ghost, no rubber-band
 *   - onPointerMove always returns null
 *   - Every Transaction is DELETE_CLIP + INSERT_CLIP(left) + INSERT_CLIP(right), per clip
 *   - New ClipIds are generated by generateId() — replaceable in tests via _setIdGenerator()
 *
 * RULES:
 *   - Zero imports from React, DOM, @webpacked-timeline/react, @webpacked-timeline/ui
 *   - ctx.modifiers.shift is the authoritative source for shift detection (not event.shiftKey)
 *   - Both halves need strictly positive duration — reject if atFrame is at clip boundary
 */

import type {
  ITool,
  ToolContext,
  TimelinePointerEvent,
  TimelineKeyEvent,
  ProvisionalState,
} from './types';
import {
  toToolId,
  type ToolId,
  type SnapPointType,
} from './types';
import type { ClipId, Clip } from '../types/clip';
import type { TrackId }      from '../types/track';
import type { TimelineFrame } from '../types/frame';
import type { Transaction }   from '../types/operations';

// ---------------------------------------------------------------------------
// ID generator (replaceable in tests — see _setIdGenerator below)
// ---------------------------------------------------------------------------

/** Production default: crypto.randomUUID() */
let generateId: () => string = () => crypto.randomUUID();

/**
 * Override the ID generator in tests for deterministic IDs.
 * Not part of the public API — exported only for test use.
 *
 * @example
 * ```typescript
 * let counter = 0;
 * beforeEach(() => { counter = 0; _setIdGenerator(() => `test-id-${++counter}`); });
 * afterEach(() => { _setIdGenerator(() => crypto.randomUUID()); });
 * ```
 */
export function _setIdGenerator(fn: () => string): void {
  generateId = fn;
}

// ---------------------------------------------------------------------------
// computeSlice — pure module-level helper, not exported
// ---------------------------------------------------------------------------

/**
 * Compute the two clip halves produced by slicing `clip` at `atFrame`.
 *
 * Returns `null` if `atFrame` is not strictly inside the clip's timeline bounds
 * (i.e. atFrame <= timelineStart or atFrame >= timelineEnd), which would produce
 * a zero-duration half.
 *
 * The caller is responsible for asserting checkInvariants on the resulting state.
 */
function computeSlice(
  clip:    Clip,
  atFrame: TimelineFrame,
): { left: Clip; right: Clip } | null {
  // Guard: atFrame must be strictly inside the clip
  if (atFrame <= clip.timelineStart || atFrame >= clip.timelineEnd) {
    return null;
  }

  const offset = (atFrame - clip.timelineStart) as TimelineFrame;
  const splitMediaPoint = (clip.mediaIn + offset) as TimelineFrame;

  const left: Clip = {
    ...clip,
    id:          generateId() as ClipId,
    timelineEnd: atFrame,
    mediaOut:    splitMediaPoint,
  };

  const right: Clip = {
    ...clip,
    id:            generateId() as ClipId,
    timelineStart: atFrame,
    mediaIn:       splitMediaPoint,
  };

  // left.mediaOut === right.mediaIn === splitMediaPoint  ✓
  return { left, right };
}

// ---------------------------------------------------------------------------
// Transaction ID counter
// ---------------------------------------------------------------------------

let _txSeq = 0;
function txId(): string { return `razor-tx-${++_txSeq}`; }

// ---------------------------------------------------------------------------
// RazorTool
// ---------------------------------------------------------------------------

export class RazorTool implements ITool {
  readonly id:          ToolId = toToolId('razor');
  readonly shortcutKey: string = 'b';   // 'b' for blade — standard NLE shortcut

  // ── Instance variables ────────────────────────────────────────────────────
  // Two vars only. The slice happens at pointerUp, not pointerDown.
  // We store the snapped frame at down-time so we don't re-snap at up-time.

  /** Snapped slice frame captured at onPointerDown. */
  private pendingFrame:  TimelineFrame | null = null;

  /** ClipId hit at onPointerDown. null if clicking empty space or for shift+all. */
  private pendingClipId: ClipId        | null = null;

  // ── ITool: getCursor ──────────────────────────────────────────────────────

  getCursor(_ctx: ToolContext): string {
    return 'crosshair';   // always — no state-dependent cursor changes
  }

  // ── ITool: getSnapCandidateTypes ─────────────────────────────────────────

  getSnapCandidateTypes(): readonly SnapPointType[] {
    return ['ClipStart', 'ClipEnd', 'Playhead', 'Marker'];
  }

  // ── ITool: onPointerDown ──────────────────────────────────────────────────

  onPointerDown(event: TimelinePointerEvent, ctx: ToolContext): void {
    // Snap the frame at click time, excluding the clicked clip's own edges
    // (snapping to its own start/end would produce a zero-duration half)
    const exclusion = event.clipId !== null ? [event.clipId] : [];
    this.pendingFrame  = ctx.snap(event.frame, exclusion);
    this.pendingClipId = event.clipId;
  }

  // ── ITool: onPointerMove ──────────────────────────────────────────────────

  onPointerMove(_event: TimelinePointerEvent, _ctx: ToolContext): ProvisionalState | null {
    // The cursor line (blade preview) is a UI rendering concern — not ProvisionalState.
    // Tools never manage cursor-line rendering directly.
    return null;
  }

  // ── ITool: onPointerUp ────────────────────────────────────────────────────

  onPointerUp(event: TimelinePointerEvent, ctx: ToolContext): Transaction | null {
    // Capture instance state before resetting (pattern from SelectionTool)
    const atFrame     = this.pendingFrame;
    const clipId      = this.pendingClipId;

    // Reset immediately — onPointerUp must never leave stale state
    this.pendingFrame  = null;
    this.pendingClipId = null;

    if (atFrame === null) return null;

    // ── Shift+click: slice ALL clips at atFrame across ALL tracks ──────────
    if (ctx.modifiers.shift) {
      return this._sliceAllTracks(atFrame, ctx);
    }

    // ── Single clip slice ──────────────────────────────────────────────────
    if (clipId === null) return null;   // clicked empty space, no shift

    const clip = this._findClip(clipId, ctx);
    if (!clip) return null;

    const sliced = computeSlice(clip, atFrame);
    if (!sliced) return null;   // atFrame at boundary — would produce zero-duration half

    return {
      id:        txId(),
      label:     'Razor',
      timestamp: Date.now(),
      operations: [
        { type: 'DELETE_CLIP', clipId: clip.id },
        { type: 'INSERT_CLIP', clip: sliced.left,  trackId: clip.trackId },
        { type: 'INSERT_CLIP', clip: sliced.right, trackId: clip.trackId },
      ],
    };
  }

  // ── ITool: onKeyDown / onKeyUp ────────────────────────────────────────────

  onKeyDown(_event: TimelineKeyEvent, _ctx: ToolContext): Transaction | null {
    return null;
  }

  onKeyUp(_event: TimelineKeyEvent, _ctx: ToolContext): void {}

  // ── ITool: onCancel ───────────────────────────────────────────────────────
  /**
   * Reset ALL instance state.
   * Every instance variable must appear here.
   */
  onCancel(): void {
    this.pendingFrame  = null;
    this.pendingClipId = null;
  }

  // ── Private helpers ───────────────────────────────────────────────────────

  private _findClip(clipId: ClipId, ctx: ToolContext): Clip | undefined {
    for (const track of ctx.state.timeline.tracks) {
      const clip = track.clips.find(c => c.id === clipId);
      if (clip) return clip;
    }
    return undefined;
  }

  /**
   * Slice every clip that contains `atFrame` across all tracks.
   * Groups operations per-clip: DELETE then INSERT left then INSERT right.
   * Tracks where no clip spans `atFrame` contribute zero operations.
   */
  private _sliceAllTracks(
    atFrame: TimelineFrame,
    ctx:     ToolContext,
  ): Transaction | null {
    type Op =
      | { type: 'DELETE_CLIP'; clipId: ClipId }
      | { type: 'INSERT_CLIP'; clip: Clip; trackId: TrackId };

    const operations: Op[] = [];

    for (const track of ctx.state.timeline.tracks) {
      for (const clip of track.clips) {
        // Only slice clips that strictly contain atFrame
        const sliced = computeSlice(clip, atFrame);
        if (!sliced) continue;   // atFrame outside this clip's bounds — skip

        operations.push(
          { type: 'DELETE_CLIP', clipId: clip.id },
          { type: 'INSERT_CLIP', clip: sliced.left,  trackId: track.id },
          { type: 'INSERT_CLIP', clip: sliced.right, trackId: track.id },
        );
      }
    }

    if (operations.length === 0) return null;   // nothing was sliced

    const clipCount = operations.length / 3;    // always a multiple of 3

    return {
      id:        txId(),
      label:     `Razor — All Tracks (${clipCount} clip${clipCount === 1 ? '' : 's'})`,
      timestamp: Date.now(),
      operations,
    };
  }
}
